language: elixir
elixir:
  - 1.3.3
otp_release:
  - 19.0

install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - mix test
notifications:
  recipients:
    - kelostrada@gmail.com